import type { Metadata } from "next";
import "./globals.css"
import {Lato} from "next/font/google" 
import Provider from "@/redux/provider";
import { ToastSetup } from "./utils";
const lato = Lato({
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Chapterwise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} antialiased`}
      >
        <Provider>
          <ToastSetup/>
          <div>
           {children}
          </div>
        </Provider>
      
      </body>
    </html>
  );
}
